project:
  type: website

website:
  title: "Julio Salazar"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: projects.qmd
        text: Projects
      - href: writing.qmd
        text: Writing
      - href: complex-systems.qmd
        text: Complex Systems
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
