project:
  type: website

website:
  title: "Julio Salazar"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: projects.qmd
        text: Projects
      - href: writing.qmd
        text: Writing
      - href: complex-systems/index.qmd
        text: Complex Systems
      - href: about.qmd
        text: About

  sidebar:
    - id: complex-systems
      title: "Complex Systems"
      style: floating
      contents:
        - href: complex-systems/index.qmd
          text: Inicio

        - section: "Ensayos"
          href: complex-systems/ensayos/index.qmd
          contents:
            - href: complex-systems/ensayos/ensayo-01/index.qmd
              text: "Ensayo 1"
            - href: complex-systems/ensayos/ensayo-02/index.qmd
              text: "Ensayo 2"
            - href: complex-systems/ensayos/ensayo-02/index.qmd
              text: "Ensayo 3"
            - href: complex-systems/ensayos/ensayo-04/index.qmd
              text: "Ensayo 4"
            - href: complex-systems/ensayos/ensayo-05/index.qmd
              text: "Ensayo 5"

        - section: "Prácticas computacionales"
          href: complex-systems/practicas/index.qmd
          contents:
            - href: complex-systems/practicas/mapeo-logistico/index.ipynb
              text: "Mapeo logístico"

        - href: complex-systems/seminario/index.qmd
          text: Seminario

        - href: complex-systems/proyecto-final/index.qmd
          text: Proyecto final

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true